Exam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404


urlpatterns = [
    path('', include('MySite.urls')),
    path('admin/log', admin.site.urls),
]

MySite/urls.py
from django.urls import path
from django.contrib.auth import views

from .views import register, home, create_task, list_task, logout_view, task_detail_view, edit_profile, user_profile, \
    freelancers_list
from .views import UserLoginView, edit_portfolio, search_task, processing_task, dialog_list, dialog_view

app_name = "mysite"
urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', logout_view, name='logout'),
    path('project/create/', create_task, name='create_task'),
    path('project/list/', list_task, name='list_task'),
    path('project/view/<int:pk>/', task_detail_view, name='detail_task'),
    path('project/select/', processing_task, name='processing_task'),
    path('profile/edit', edit_profile, name='edit_profile'),
    path('freelancers/', freelancers_list, name='freelancers'),
    path('edit/portfolio/', edit_portfolio, name='edit_portfolio'),
    path('project/search/', search_task, name='project_search'),
    path('dialog/list/', dialog_list, name='dialog_list'),
    path('dialog/view/<int:chat_id>/', dialog_view, name='dialog_view'),
    path('<str:username>/', user_profile, name='profile'),
]

MySite/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now


class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('customer', 'Customer'),
        ('executor', 'Executor'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='customer')

    def __str__(self):
        return self.username

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_permissions',  # Устанавливаем уникальное имя для связи
        blank=True
    )

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_groups',  # Уникальное имя для связи
        blank=True
    )

    def is_customer(self):
        return self.role == 'customer'

    def is_executor(self):
        return self.role == 'executor'


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class ExecutorPortfolio(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name="executor_portfolio")
    skills = models.CharField(max_length=100, help_text="List of skills", blank=True, null=True)
    categories = models.ManyToManyField(Category, related_name="categories_sk")
    experience = models.TextField(help_text="Description of experience or info about you", blank=True)
    portfolio = models.TextField(help_text="Portfolio or projects links", blank=True)
    like = models.IntegerField(help_text="Likes rating", default=0)
    dislike = models.IntegerField(help_text="Likes rating", default=0)
    completed_tasks = models.IntegerField(help_text="Likes rating", default=0)


class CustomerPortfolio(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='customer_portfolio')


class Task(models.Model):
    STATUS_CHOICES = [
        ('active', 'Активный'),
        ('inactive', 'Неактивный'),
        ('in_progress', 'В работе'),
        ('completed', 'Завершён'),
    ]
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="tasks")
    executor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="tasks_on_work", null=True)
    categories = models.ManyToManyField(Category, default="Not have categories", related_name="task_category")
    key_words = models.CharField(max_length=50, help_text='specialization')
    title = models.CharField(max_length=100, help_text="Name of the task")
    description = models.TextField(help_text="Description of your task")
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text="Price")
    deadline = models.DateTimeField(help_text="Your deadline")
    create_at = models.DateTimeField(auto_now_add=True, help_text='Created time')
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='active',
        help_text="status of task"
    )


class Chat(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="task_chats", help_text="Chat for this task")
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='customer_chats')
    executor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='executor_chats')
    created_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True, help_text="Is the chat open?")

    def __str__(self):
        return f"Chat with {self.customer}(customer) and {self.executor}(executor)"


class Message(models.Model):
    chat = models.ForeignKey(
        Chat,
        on_delete=models.CASCADE,
        related_name="messages",
        help_text="Chat to which this message belongs",
    )
    sender = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="sender",
        help_text="User who sent the message",
    )
    content = models.TextField(help_text="Message content")
    timestamp = models.DateTimeField(help_text="Time when the message was send", auto_now_add=True)
    is_read = models.BooleanField(default=False, help_text="Has the message been read?")

    def __str__(self):
        return f"Message from {self.sender.username} in chat {self.chat.id}"


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="comments")
    executor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="comments")
    content = models.CharField(max_length=200, help_text="type your text")
    offer = models.IntegerField(default=0, help_text="Your proposal")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['task', 'executor'], name='unique_task_executor_comment')
        ]

MySite/forms.py
from django import forms
from .models import CustomUser, Task, Category, ExecutorPortfolio, Comment, Message
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'role']


class TaskCreateForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    deadline = forms.DateField(
        widget=forms.SelectDateWidget(),  # Виджет для выбора даты
        required=True
    )

    price = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={'placeholder': 'Введите цену', 'step': '0.01', 'min': '0', 'style': 'text-align:right;'}),
        required=True
    )

    class Meta:
        model = Task
        fields = ['categories', 'key_words', 'title', 'description', 'price', 'deadline']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }


class EditPortfolioForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),  # Все категории из базы данных
        widget=forms.CheckboxSelectMultiple,  # Виджет для множественного выбора
        required=False  # Поле не обязательно
    )

    class Meta:
        model = ExecutorPortfolio
        fields = ['categories', 'skills', 'experience', 'portfolio']


class TaskFilterForm(forms.Form):
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple,
                                                required=False)
    key_words = forms.CharField(max_length=100, required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'offer']


class MessageForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control form-control-sm', 'style': 'height: 50px;'}))
    class Meta:
        model = Message
        fields = ['content']

MySite/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.db.models import Q

from .forms import UserRegistrationForm, TaskCreateForm, UserEditForm, EditPortfolioForm, TaskFilterForm, CommentForm, \
    MessageForm
from .models import CustomUser, Task, ExecutorPortfolio, Comment, Chat, Message
from .decorators import role_required, anonymous_required


@method_decorator(anonymous_required, name='dispatch')
class UserLoginView(LoginView):
    template_name = "mysite/login.html"


# Представление выхода с аккаунта
def logout_view(request):
    logout(request)
    return redirect('mysite:login')


# Регистрация нового пользователя
@anonymous_required  # декоратор где ограничивает залогиненых юзеров
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('mysite:home'))
        else:
            form = UserRegistrationForm()
            return render(request, 'mysite/register.html',
                          {'form': form, 'error': 'Wrong registrations!!!', })

    else:
        form = UserRegistrationForm()
        return render(request, 'mysite/register.html', {'form': form})


# обычный View для главной страницы
def home(request):
    users = CustomUser.objects.all()
    user = request.user
    return render(request, 'mysite/home.html', {'users': users, 'user': user})


# Представление создания нового задания
# Ограничения декораторов: залогиненых и только с ролью customer
@login_required
@role_required('customer')
def create_task(request):
    if request.method == 'POST':
        form = TaskCreateForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.customer = request.user
            task.save()
            categories = form.cleaned_data.get('categories')
            task.categories.set(categories)
            return redirect(reverse('mysite:list_task'))
        else:
            form = TaskCreateForm()
            return render(request, 'mysite/create_task.html',
                          {'form': form, 'error': 'Wrong Task!!!', })
    else:
        form = TaskCreateForm()
        return render(request, 'mysite/create_task.html', {'form': form})


# Просмотр своих существуещих обьявлений customer
@login_required
@role_required('customer')
def list_task(request):
    tasks = Task.objects.filter(customer=request.user).order_by('-id')[:15]
    return render(request, 'mysite/list_task.html', {'tasks': tasks})


# Просмотр более детального просмотра одного Task
@login_required
def task_detail_view(request, pk, executor_id=None):
    task = get_object_or_404(Task, pk=pk)
    comments = task.comments.all()

    if task.status == 'active':
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.task = task
                comment.executor = request.user
                comment.save()
                return redirect('mysite:detail_task', pk=pk)
            else:
                form = CommentForm()
            return render(request, 'mysite/detail_task.html', {'task': task, 'comments': comments, 'form': form,
                                                               'error': 'Wrong comment'})
        if request.user.is_executor():
            if comments.filter(executor=request.user).exists():
                return render(request, 'mysite/detail_task.html', {'task': task, 'comments': comments})
            else:
                form = CommentForm()
                return render(request, 'mysite/detail_task.html', {'task': task, 'comments': comments,
                                                                   'form': form})
        return render(request, 'mysite/detail_task.html', {'task': task, 'comments': comments})
    else:
        return render(request, 'mysite/detail_task.html', {'task': task})


# Нужен для того чтобы поменять статус тасков. Например если в процессе работы завершить
@login_required
def processing_task(request):
    task_id = request.POST.get('task_id')
    executor_id = request.POST.get('executor_id')

    task = Task.objects.get(id=task_id)
    executor = CustomUser.objects.get(id=executor_id)

    if request.user != task.customer:
        return HttpResponse('Вы не можете выбрать исполнителя для этой задачи.', status=403)

    if task.status == 'active':
        task.executor = executor
        task.status = 'in_progress'
        chat = Chat(customer=task.customer, executor=task.executor, task=task)
        chat.save()
        task.save()
    elif task.status == 'in_progress':
        task.status = 'completed'
        task.executor.executor_portfolio.completed_tasks += 1
        task.executor.executor_portfolio.save()
        task.save()

    return redirect('mysite:detail_task', pk=task_id)


# Представление для редакции профиля
@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('mysite:home')
        else:
            form = UserEditForm(instance=user)
            return render(request, 'mysite/edit_profile.html', {'form': form, 'error': 'Error form!'})
    else:
        form = UserEditForm(instance=user)
        return render(request, 'mysite/edit_profile.html', {'form': form})


# Просмотр профиля любого
def user_profile(request, username):
    user = get_object_or_404(CustomUser, username=username)
    executor_profile = None

    if hasattr(user, "executor_portfolio"):
        executor_profile = user.executor_portfolio

    return render(request, 'mysite/profile.html', {'user': user, 'profile': executor_profile})


# Вывод списка фрилансеров
def freelancers_list(request):
    executors = CustomUser.objects.filter(role='executor')
    return render(request, 'mysite/freelancers.html', {'users': executors})


# Редактировать портофолио для Исполнителя и только
@login_required
@role_required('executor')
def edit_portfolio(request):
    if request.method == 'POST':
        form = EditPortfolioForm(request.POST)
        if form.is_valid():
            portfolio, created = ExecutorPortfolio.objects.update_or_create(
                user=request.user,
                defaults={
                    'skills': form.cleaned_data['skills'],
                    'experience': form.cleaned_data['experience'],
                    'portfolio': form.cleaned_data['portfolio'],
                }
            )
            portfolio.categories.set(form.cleaned_data['categories'])
            return redirect(reverse('mysite:profile', kwargs={'username': request.user.username}))
        else:
            form = EditPortfolioForm()
            return render(request, 'mysite/edit_portfolio.html',
                          {'form': form, 'error': 'Wrong Task!!!', })
    else:
        form = EditPortfolioForm()
        return render(request, 'mysite/edit_portfolio.html', {'form': form})


# Страница поиска любого задания на сайте
@login_required
def search_task(request):
    form = TaskFilterForm(request.GET)
    tasks = Task.objects.all()

    if form.is_valid():
        categories = form.cleaned_data.get('categories')
        if categories:
            tasks = tasks.filter(categories__in=categories).distinct()

        key_words = form.cleaned_data.get('key_words')
        if key_words:
            tasks = tasks.filter(key_words__icontains=key_words)

    return render(request, 'mysite/search_task.html', {'form': form, 'tasks': tasks})


# Выводим список переписок пользователя
@login_required
def dialog_list(request):
    chats = Chat.objects.filter(Q(customer=request.user) | Q(executor=request.user))[:20]
    if request.user.role == 'executor':
        role = 'executor'
    else:
        role = 'customer'
    return render(request, 'mysite/dialog_list.html', {'chats': chats, 'role': role})


# Крутая функция, горд собой! Выводит чат с связанным собеседником
@login_required
def dialog_view(request, chat_id):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            message.chat = get_object_or_404(Chat, pk=chat_id)
            message.save()
    messages = Message.objects.filter(chat=chat_id).order_by('timestamp')[:20]
    form = MessageForm()
    return render(request, 'mysite/dialog_view.html', {'messages': messages, 'form': form, 'id': chat_id})

templates/mysite/create_task.html
{% extends "mysite/base.html" %}


{% block content %}
    {% if error %}
    <h3>{{ error }}</h3>
    {% endif %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Публиковать</button>
</form>
{% endblock %}

templates/mysite/detail_task.html
{% extends "mysite/base.html" %}

{% block title %}Список заданий{% endblock %}

{% block content %}
<div class="border-bottom pb-3 mb-3">
    <h1 class="mb-3">Задача: {{ task.title }}</h1>
    <p><strong>Описание:</strong> {{ task.description }}</p>
    <p><strong>Цена:</strong> {{ task.price }}</p>
    <p><strong>Срок выполнения:</strong> {{ task.deadline }}</p>

    {% if task.key_words %}
    <p><strong>Ключевые слова:</strong> {{ task.key_words }}</p>
    {% endif %}

    {% if task.categories.all %}
    <p><strong>Категории:</strong>
        {% for category in task.categories.all %}
        <span class="badge bg-primary">{{ category.name }}</span>
        {% endfor %}
    </p>
    {% endif %}

    {% if task.status == 'active' %}
    <p class="bg-success text-white p-2 rounded d-inline-block">Активный</p>
    {% elif task.status == 'inactive' %}
    <p class="bg-danger text-white p-2 rounded d-inline-block">Неактивный</p>
    {% elif task.status == 'in_progress' %}
    <p class="bg-warning text-white p-2 rounded d-inline-block">В работе</p>
    {% elif task.status == 'completed' %}
    <p class="bg-primary text-white p-2 rounded d-inline-block">Завершен</p>
    {% endif %}


    {% if request.user == task.customer %}
    {% if task.status == 'in_progress' %}
    <a href="{% url 'mysite:dialog_view' task.task_chats.first.id %}" style="color: black">К диалогу</a>
    <form action="{% url 'mysite:processing_task' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="task_id" value="{{ task.id }}">
        <input type="hidden" name="executor_id" value="{{ task.executor.id }}">
        <button type="submit">Завершить</button>
    </form>
    {% endif %}
    {% endif %}

</div>

<div class="mt-4">
    <h2>Комментарии</h2>
    {% for comment in comments %}
    <div class="border rounded p-3 mb-3">
        <h3>
            <a class="text-decoration-none text-primary" href="{% url 'mysite:profile' comment.executor.username %}">
                {{ comment.executor.username }}
            </a>
        </h3>
        <p class="mb-2">{{ comment.content }}</p>
        <p><strong>Предложение:</strong> {{ comment.offer }}</p>
        {% if request.user == task.customer %}
        <form method="POST" action="{% url 'mysite:processing_task' %}">
            {% csrf_token %}
            <input type="hidden" name="task_id" value="{{ task.id }}">
            <input type="hidden" name="executor_id" value="{{ comment.executor.id }}">
            <button type="submit" class="btn btn-success">Выбрать</button>
        </form>
        {% endif %}
    </div>
    {% empty %}
    <p class="text-muted">Нет комментариев для этой задачи.</p>
    {% endfor %}
</div>

<div class="mt-4">
    {% if form %}
    <h2>Оставить комментарий</h2>
    <form method="post" class="border rounded p-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Отправить</button>
    </form>
    {% endif %}
</div>
{% endblock %}

templates/mysite/dialog_list.html
{% extends "mysite/base.html" %}
{% load static %}

{% block title %}Dialog List{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Dialog List</h1>
    <div class="row">
        {% if role == 'executor' %}
        {% for chat in chats %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-body d-flex align-items-center">
                    <img src="{% static 'images/avatar.png' %}" class="rounded-circle me-3" alt="Avatar" width="50"
                         height="50">
                    <div>
                        <a href="{% url 'mysite:dialog_view' chat.id %}">
                            <p class="mb-0 fw-bold text-dark bg-light p-2 rounded"
                               style="box-shadow: 1px 1px 5px rgba(0, 0, 0, 0.3);">{{ chat.executor.first_name }}
                                {{ chat.executor.last_name }}</p>
                        </a>

                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12 text-center">
            <h2 class="text-muted">Пока диалогов нету</h2>
        </div>
        {% endfor %}
        {% else %}
        {% for chat in chats %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-body d-flex align-items-center">
                    <img src="{% static 'images/avatar.png' %}" class="rounded-circle me-3" alt="Avatar" width="50"
                         height="50">
                    <div>
                        <a href="{% url 'mysite:dialog_view' chat.id %}">
                            <p class="mb-0 fw-bold text-dark bg-light p-2 rounded"
                               style="box-shadow: 1px 1px 5px rgba(0, 0, 0, 0.3);">{{ chat.executor.first_name }}
                                {{ chat.executor.last_name }}</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12 text-center">
            <h2 class="text-muted">Пока диалогов нету</h2>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

templates/mysite/dialog_view.html
{% extends "mysite/base.html" %}
{% load static %}

{% block title %}Dialog View{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Chat</h4>
                </div>
                <div class="card-body" style="max-height: 400px; overflow-y: auto;">
                    {% for message in messages %}
                        {% if message.sender == request.user %}
                            <div class="d-flex justify-content-end mb-3">
                                <div class="bg-primary text-white p-2 rounded">
                                    <p class="mb-0">{{ message.content }}</p>
                                </div>
                            </div>
                        {% else %}
                            <div class="d-flex justify-content-start mb-3">
                                <div class="bg-light p-2 rounded">
                                    <p class="mb-0">{{ message.content }}</p>
                                </div>
                            </div>
                        {% endif %}
                    {% empty %}
                        <p class="text-center text-muted">Пока пусто :(</p>
                    {% endfor %}
                </div>
                <div class="card-footer">
                    <form action="{% url 'mysite:dialog_view' id %}" method="post" class="d-flex">
                        {% csrf_token %}
                        {{ form.as_table }}
                        <button type="submit" class="btn btn-primary ms-2">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/mysite/edit_portfolio.html
{% extends "mysite/base.html" %}

{% block title %}Edit profile {% endblock %}

{% block content %}
{% if error %}
<h2 style="color: red;"><strong>{{error}}</strong></h2>
{% endif %}
<form action="{% url 'mysite:edit_portfolio' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >SEND</button>
</form>
{% endblock %}

templates/mysite/edit_profile.html
{% extends "mysite/base.html" %}

{% block title %}Edit profile {% endblock %}

{% block content %}
{% if error %}
<h2 style="color: red;"><strong>{{error}}</strong></h2>
{% endif %}
<form action="{% url 'mysite:edit_profile' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >SEND</button>
</form>
{% endblock %}

templates/mysite/freelancers.html
{% extends "mysite/base.html" %}

{% block title %}Freelancers{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Список фрилансеров</h1>
    <div class="row">
        {% for user in users %}
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ user.username }}</h5>
                        <p class="card-text">
                            <strong>Имя:</strong> {{ user.first_name }} {{ user.last_name }}<br>
                            <strong>Email:</strong> {{ user.email }}
                        </p>
                        <a href="{% url 'mysite:profile' user.username %}" class="btn btn-primary">Посмотреть профиль</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Фрилансеры не найдены.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/mysite/home.html
{% extends "mysite/base.html" %}

{% block title %}Главная Страница{% endblock %}



{% block content %}
<!-- Features Section -->
    <section id="features" class="py-5">
        <div class="container">
            <h2 class="text-center mb-4">Почему выбирают нашу платформу</h2>
            <div class="row text-center">
                <div class="col-md-3">
                    <div class="card p-3 border-0">
                        <div class="card-body">
                            <h5 class="card-title">Простота</h5>
                            <p class="card-text">Интуитивно понятный интерфейс.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card p-3 border-0">
                        <div class="card-body">
                            <h5 class="card-title">Безопасность</h5>
                            <p class="card-text">Эскроу-система защищает сделки.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card p-3 border-0">
                        <div class="card-body">
                            <h5 class="card-title">Большая база</h5>
                            <p class="card-text">Тысячи проверенных исполнителей.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card p-3 border-0">
                        <div class="card-body">
                            <h5 class="card-title">Поддержка</h5>
                            <p class="card-text">Круглосуточная помощь пользователей.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/mysite/login.html
{% extends "mysite/base.html" %}



{% block content %}
<h1>Login</h1>
{% if error %}
<h2 style="color: red;">{{ error }}</h2>
{% endif %}
<form action="{% url 'mysite:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>

<p>or <a href="/register" style="color: blue;">Register</a></p>
{% endblock %}

templates/mysite/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
    <h1>You need be login</h1>
    <a href="{% url mysite:login %}">Login</a>
</body>
</html>

templates/mysite/profile.html
{% extends "mysite/base.html" %}

{% block title %}Profile{% endblock %}


{% block content %}
<div class="container">
    <h1>Данные пользователя: {{ user.username }}</h1>
    <p><strong>Имя:</strong> {{ user.first_name }}</p>
    <p><strong>Фамилия:</strong> {{ user.last_name }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
</div>
{% if request.user == user %}
<a href="{% url 'mysite:edit_profile' %}" class="btn btn-primary">Редактировать</a>
{% endif %}


{% if profile %}
<hr>
<h2>Профиль исполнителя</h2>
<p><strong>Описание:</strong> {{ profile.description }}</p>
<p><strong>Категории:</strong>
    {% for category in profile.categories.all %}
    {{ category.name }}{% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p><strong>Скиллы:</strong>{{ profile.skills }}</p>
<p><strong>Опыт работы:</strong>{{ profile.experience }}</p>
<p>
    <strong>Оценки:</strong>
    <span class="text-success">{{ profile.like }}</span> /
    <span class="text-danger">{{ profile.dislike }}</span>
</p>
<p><strong>Выполнено задач:</strong> {{ profile.completed_tasks }}</p>
{% if request.user == user %}
<a href="{% url 'mysite:edit_portfolio' %}" class="btn btn-primary">Редактировать</a>
{% endif %}
{% endif %}
{% endblock %}

templates/mysite/register.html
{% extends "mysite/base.html" %}


{% block content %}
<h2>Registration</h2>
{% if error %}
<h2 style="color: red;">{{ error }}</h2>
{% endif %}
<form action="{% url 'mysite:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>
<p>or <a href="/login" style="color: blue;">login</a></p>
{% endblock %}